# Generated by Django 5.2.4 on 2025-07-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Start Load Time')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finish Load Time')),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('ERROR', 'Error'), ('PENDING', 'Pendente')], max_length=20, verbose_name='Status')),
                ('events_imported_count', models.PositiveIntegerField(default=0, verbose_name='Events Imported Count')),
            ],
            options={
                'verbose_name': 'Load Batch',
                'verbose_name_plural': 'Load Batches',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True, verbose_name='Event ID')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('event_type', models.CharField(choices=[('PRESENTIAL', 'Presencial'), ('ONLINE', 'Online')], max_length=20, verbose_name='Event Type')),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Venue Name')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('sub_category', models.CharField(max_length=100, verbose_name='Sub Category')),
                ('load_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.loadbatch')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
            },
        ),
    ]
