# Generated by Django 5.2.4 on 2025-07-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadbatch',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Sucesso'), ('ERROR', 'Error'), ('PENDING', 'Pendente')], max_length=20, verbose_name='Status'),
        ),
    ]
