version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    command: gunicorn sympla_integration.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 300
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:


